theme: jekyll-theme-minimal
title: Social Distance and Digital Wellbeing
description: Master's research project run by Jacob Saindon, University of Kentucky Geography M.A. Student, and supervised by Matthew W. Wilson, PhD, Associate Professor of Geography at the University of Kentucky
