theme: jekyll-theme-minimal
title: Social Distance and Digital Wellbeing
description: Research project run by <a href="https://geography.as.uky.edu/users/jsa324" target="_blank">Jacob Saindon</a>, M.A. Student at the University of Kentucky, and supervised by <a href="https://geography.as.uky.edu/users/mwwi222" target="_blank">Dr. Matthew W. Wilson</a>, PhD, Associate Professor of Geography at the University of Kentucky
github: is\_project\_page:false
