theme: jekyll-theme-minimal
title: Social Distance and Digital Wellbeing
description: MA research project run by <a href="https://geography.as.uky.edu/users/jsa324">Jacob Saindon</a>, Geography M.A. Student at the University of Kentucky<br>Supervised by <a href="https://geography.as.uky.edu/users/mwwi222">Dr. Matthew W. Wilson</a>, PhD, Associate Professor of Geography at the University of Kentucky
